[package]
name = "day_5"
version = "0.2.0"
authors = ["denaun"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33"
env_logger = "0.7"
log = "0.4"
snafu = "0.6"