[package]
name = "day_12"
version = "0.2.0"
authors = ["Denaun <mauzuc90@yahoo.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "^0.2"
gcd = "^2.0"

[dev-dependencies]
regex = "^1.3"
