[package]
name = "day_7"
version = "0.1.0"
authors = ["denaun"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day_5 = { path = "../day_5" }
clap = "^2.33"
env_logger = "0.7"
log = "0.4"
permutator = "0.4.0"
